controllers/SitioController.php
<?php
/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 10/01/17
 * Time: 05:26 PM
 */

namespace app\controllers;

use app\models\ContactForm;
use app\models\EmpresaTelecliente;
use app\models\LoginForm;
use app\models\Newpass;
use app\models\SignupForm;
use app\models\UserRepass;
use app\models\Usuario;
use Yii;
use yii\db\Connection;
use yii\helpers\Json;
use yii\web\Controller;

class SitioController extends Controller
{
  public $layout = 'mainFront';

  public function actionIndex()
  {
    return $this->render('index', [
      'modelContact' => new ContactForm(),
    ]);
  }

  public function actionRegistrar()
  {
    $registro = new SignupForm();
    $empresaTelecliente = new EmpresaTelecliente();
    if ($registro->load(Yii::$app->request->post()) and
      $empresaTelecliente->load(Yii::$app->request->post())
    ) {
      if ($registro->validate() and $empresaTelecliente->validate(['nombre'])) {
        $empresaTelecliente->conexion = 'Preparando...';
        $empresaTelecliente->config = Json::encode(['nombre' => $empresaTelecliente->nombre]);
        $empresaTelecliente->save();
        $empresaTelecliente->conexion = [
          'dsn' => 'mysql:host=localhost;dbname=teleclientes_empresa_' . $empresaTelecliente->id,
          'username' => 'teleclt_user_' . $empresaTelecliente->id,
          'password' => Yii::$app->security->generateRandomString(10),
          'charset' => 'utf8',
        ];
        $cpaneluser = 'merkapuntos';

        $function = [
          'db' => 'teleclientes_empresa_' . $empresaTelecliente->id,
          'cpanel_jsonapi_user' => $cpaneluser,
          'cpanel_jsonapi_module' => 'MysqlFE',
          'cpanel_jsonapi_func' => 'createdb',
          'cpanel_jsonapi_apiversion' => 2
        ];
        $params = http_build_query($function, '', '&');
        $url = "https://p3plcpnl0604.prod.phx3.secureserver.net:2083/json-api/cpanel?$params";
        $result = $this->getCurl($url);
        Yii::info(Json::decode($result));


        $function = [
          'dbuser' => $empresaTelecliente->conexion['username'],
          'password' => $empresaTelecliente->conexion['password'],
          'cpanel_jsonapi_user' => $cpaneluser,
          'cpanel_jsonapi_module' => 'MysqlFE',
          'cpanel_jsonapi_func' => 'createdbuser',
          'cpanel_jsonapi_apiversion' => 2
        ];
        $params = http_build_query($function, '', '&');
        $url = "https://p3plcpnl0604.prod.phx3.secureserver.net:2083/json-api/cpanel?$params";
        $result = $this->getCurl($url);
        Yii::info(Json::decode($result));

        $function = [
          'db' => 'teleclientes_empresa_' . $empresaTelecliente->id,
          'dbuser' => $empresaTelecliente->conexion['username'],
          'password' => $empresaTelecliente->conexion['password'],
          'privileges' => 'ALL%20PRIVILEGES',
          'cpanel_jsonapi_user' => $cpaneluser,
          'cpanel_jsonapi_module' => 'MysqlFE',
          'cpanel_jsonapi_func' => 'setdbuserprivileges',
          'cpanel_jsonapi_apiversion' => 2
        ];
        $params = http_build_query($function, '', '&');
        $url = "https://p3plcpnl0604.prod.phx3.secureserver.net:2083/json-api/cpanel?$params";
        $result = $this->getCurl($url);
        Yii::info(Json::decode($result));


        $conn = new Connection($empresaTelecliente->conexion);
        $sql = file_get_contents('teleclientes.sql');
        $conn->createCommand($sql)->execute();

        $oldDB = Yii::$app->db;
        Yii::$app->db = $conn;
        $user = $registro->signup();
        Yii::$app->db = $oldDB;
        $empresaTelecliente->conexion = Json::encode($empresaTelecliente->conexion);
        $empresaTelecliente->save();
        Yii::$app->db = $conn;
        Yii::$app->authManager->db = $conn;
        Yii::$app->authManager->assign(Yii::$app->authManager->getRole('Administrador'),$user->id);
        Yii::$app->user->login($user, 20000);
        Yii::$app->session->set('empresa_id', $empresaTelecliente->id);
        return $this->redirect(['site/index'])->send();
      }
    }
    return $this->render('registro', [
      'registro' => $registro,
      'empresa' => $empresaTelecliente
    ]);
  }

  private function getCurl($url)
  {
    Yii::info($url);
    $user = "merkapuntos";
    $auth = "guillermo1!A";
    $auth = 'Authorization: Basic ' . base64_encode($user . ':' . $auth) . "\r\n";
    $header[0] = $auth .
      "Content-Type: application/x-www-form-urlencoded\r\n" .
      "Content-Length: " . strlen($url) . "\r\n" . "\r\n" . $url;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
    return curl_exec($ch);
  }

  public function actionLogin()
  {
    $empresas = EmpresaTelecliente::find()->asArray()->all();
    if (Yii::$app->session->get('empresa_id', false)) {
      return $this->redirect(['site/index']);
    }

    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->redirect(['site/access']);
    }
    return $this->render('login', [
      'model' => $model,
      'empresas' => $empresas
    ]);
  }

  public function actionRecordarContrasena()
  {
    $empresas = EmpresaTelecliente::find()->asArray()->all();
    $model = new UserRepass();
    if ($model->load(Yii::$app->request->post())) {

      if ($model->enviarEmail()) {
        Yii::$app->session->setFlash('success', 'Su contraseña ha sido enviada a su correo');
      }
    }
    return $this->render('recordar_contrasena', [
      'model' => $model,
      'empresas' => $empresas
    ]);
  }

  public function actionRecuperarContrasena($token, $empresa_id)
  {
    $empresa = EmpresaTelecliente::findOne($empresa_id);
    $user = null;
    $model = new Newpass();
    if ($empresa != null) {
      Yii::$app->db = new Connection(Json::decode($empresa->conexion));
      $user = Usuario::findOne(['password_reset_token' => $token]);
      if ($user != null and Usuario::isPasswordResetTokenValid($user->password_reset_token)) {
        if ($model->load(Yii::$app->request->post())) {
          if ($model->validate()) {
            $user->removePasswordResetToken();
            $user->setPassword($model->password);
            $user->save(false);
            Yii::$app->session->setFlash('success', 'Contraseña cambiada correctamente');
            return $this->redirect(['/sitio/login']);
          }
        }
      } else {
        Yii::$app->session->setFlash('danger', 'Token invalido, solicite una nueva contraseña');
        return $this->redirect(['sitio/recordar-contrasena']);
      }
    }
    return $this->render('recuperar_contrasena', [
      'empresa' => $empresa,
      'usuario' => $user,
      'model' => $model
    ]);
  }

  public function actionContacto()
  {
    return 'OK';
  }

  public function actions()
  {
    return [
      'captcha' => [
        'class' => 'yii\captcha\CaptchaAction',
        'foreColor' => 0x333333,
        'transparent' => true
      ],
    ];
  }
}

views/sitio/index.php
<?php
/**
 * User: jhon
 * Date: 10/01/17
 * Time: 05:29 PM
 * @var $this \yii\web\View
 */
use yii\helpers\Html;

$this->title = "Bienvenido a teleclientes";
?>
<section id="home" class="home-section default-bg color2">
  <div class="container">
    <div class="row">
      <div class="col-md-6 marginbot40">
        <img src="<?= \yii\helpers\Url::to("@web/theme/img/slider/mobile-phone.png") ?>" class="img-responsive" alt=""/>
      </div>
      <div class="col-md-6 home-container">
        <div class="headline">
          <h1>Teleclientes.com</h1>
          <p>El software moderno para la administración de ASC, CSA, CAS</p>
        </div>
        <p>
          Teleclientes es un software para centros de servicios de toda indole,
          refrigeración, audio-video, talleres de reparacion y mantenimiento etc.
        </p>
        <p>
          Programe mantenimientos y servicios a sus clientes en fechas especificas,
          le damos dos aplicativos diferentes para ingresos de servicios y ejecución de los mismos
          para sus mecanicos.
        </p>
        <p>
          pruebelo y nunca perdera sus cliente muy facil su manejo.
        </p>
      </div>
    </div>
  </div>
</section>
<div id="intro" class="dark-section">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-10 col-md-offset-1">
        <h4 class="headtitle">
          Lo ideal para la administracion de ASC, CSA, CAS
        </h4>
        <p>Teleclientes.com</p>
        <?= Html::a('Pidelo ahora', ['sitio/registrar'], ['class' => 'btn btn-primary btn-lg']) ?>
      </div>
    </div>
  </div>
</div>
<!-- End intro -->

<!-- Start description -->
<section id="description" class="half-wrapper">
  <div class="container half-full">
    <div class="row">
      <div class="col-md-6 half-column set-left">
        <div class="half-col-containt">
          <div class="heading">
            <h5>Descripcion</h5>
            <p>
              Teleclientes es un software ideal para la administracion de su centro de servicio
            </p>
            <span></span>
          </div>
          <p>
            Ingrese on-line las 24 horas del dia, lleve un mejor control de su centro de servicio,
            administre todo lo relacionado con su negocio de forma agil y practica a muy bajo precio.
          </p>
          <ul class="check-list">
            <li><i class="fa fa-check"></i> Acceso online las 24 horas.</li>
            <li><i class="fa fa-check"></i> Generacion de archivos PDF.</li>
            <li><i class="fa fa-check"></i> Acceso para sus clientes.</li>
            <li><i class="fa fa-check"></i> Envio de estadisticas a Marcas, Almacenes y demas para quien trabajas.</li>
            <li><i class="fa fa-check"></i> De una mejor imagen de su empresa.</li>
          </ul>
          <p class="btn-horizontal">
            <?= Html::a('Ingresar', ['/sitio/login'], ['class' => 'btn btn-primary']) ?>
          </p>
        </div>
      </div>
      <div class="col-md-6 half-column set-right">
        <div class="fluid">
          <img src="<?= \yii\helpers\Url::to("@web/theme/img/img-app01.png") ?>" class="img-responsive" alt=""/>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="features" class="half-wrapper">
  <div class="container half-full">
    <div class="row">
      <div class="col-md-6 half-column set-left">
        <div class="fluid">
          <div class="imac-wrapper">
            <div class="imac-slider">
              <div class="imac-device">
                <ul class="slides">
                  <li><img src="<?= \yii\helpers\Url::to("@web/theme/img/imac-slide/slide1.png") ?>"
                           class="img-responsive" alt=""/></li>
                  <li><img src="<?= \yii\helpers\Url::to("@web/theme/img/imac-slide/slide2.png") ?>"
                           class="img-responsive" alt=""/></li>
                  <li><img src="<?= \yii\helpers\Url::to("@web/theme/img/imac-slide/slide3.png") ?>"
                           class="img-responsive" alt=""/></li>
                </ul>
              </div>
            </div>
            <img src="<?= \yii\helpers\Url::to("@web/theme/img/imac-slider.png") ?>" class="img-responsive" alt=""/>
          </div>
        </div>
      </div>
      <div class="col-md-6 half-column set-right">
        <div class="half-col-containt">
          <div class="heading">
            <h5>Caracteristicas</h5>
            <p>
              Clave de características, esta es una de las razones por que elegir teleclientes
            </p>
            <span></span>
          </div>
          <ul class="feature-list">
            <li>
              <span class="icon-screen-desktop icon-2x icon-color icon-left"></span>
              <h5>Full responsive</h5>
              <p>
                Teleclientes funciona en todos los tamaños de pantalla
              </p>
            </li>
            <li>
              <span class="icon-wrench icon-2x icon-color icon-left"></span>
              <h5>Facil manejo</h5>
              <p>
                Su facil manejo hara que en par de dias ya estes usando el sistema perfectamente
              </p>
            </li>
            <li>
              <span class="icon-chemistry icon-2x icon-color icon-left"></span>
              <h5>Simple y Limpio</h5>
              <p>
                Es simple y accesible para cualquier operario.
              </p>
            </li>
            <li>
              <span class="icon-envelope-letter icon-2x icon-color icon-left"></span>
              <h5>Envio de correos</h5>
              <p>
                Comparte tu trabajo con las marcas y comerciantes de los equipos para quienes trabajas
              </p>
            </li>
            <li>
              <span class="icon-notebook icon-2x icon-color icon-left"></span>
              <h5>Documentacion</h5>
              <p>
                Teleclientes ofrese una documentación y tutoriales para que aprendas a usarlo rapidamente
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="pricing" class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="heading centered">
          <h5>Precios</h5>
          <p>
            Selecciona el paquete que mas te convenga
          </p>
          <span></span>
        </div>
      </div>
      <div class="col-md-4">
        <div class="pricing-wrapper">
          <div class="pricing-head">
            <span class="pricing-price">Demo</span>
            <h4>Prueba 60 dias</h4>
          </div>
          <div class="pricing-bottom">
            <?= Html::a('Probar', ['sitio/registrar'], ['class' => 'btn btn-primary']) ?>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="pricing-wrapper">
          <div class="pricing-head">
            <sup>$</sup>
            <span class="pricing-price">60 Mil</span>
            <h4>Mensual</h4>
          </div>
          <div class="pricing-bottom">
            <?= Html::a('Probar', ['sitio/comprar', 'lap' => 30], ['class' => 'btn btn-primary']) ?>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="pricing-wrapper">
          <div class="pricing-head">
            <sup>$</sup>
            <span class="pricing-price">600 mil</span>
            <h4>Pago unico anual</h4>
          </div>
          <div class="pricing-bottom">
            <?= Html::a('Probar', ['sitio/comprar', 'lap' => 12], ['class' => 'btn btn-primary']) ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="contact" class="half-wrapper">
  <div class="container half-full">
    <div class="row">
      <div class="col-md-6 half-column set-left">
        <div class="half-col-containt">
          <div class="heading">
            <h5>Contactanos</h5>
            <p>
              Si desea saber mas, no dude en preguntarnos.
            </p>
            <span></span>
          </div>
          <form id="contactform" action="<?= \yii\helpers\Url::to(['sitio/contacto']) ?>" method="post"
                class="validateform" name="leaveContact">

            <ul class="listForm">
              <li>
                <label>Name :</label>
                <input class="form-control input-name input-lg" type="text" name="name" data-rule="maxlen:4"
                       data-msg="Espacio requerido" placeholder="Por favor ingrese su nombre."/>
                <div class="validation"></div>
              </li>
              <li>
                <label>Email :</label>
                <input class="form-control input-email input-lg" type="text" name="email" data-rule="email"
                       data-msg="Por favor ingrese un correo para ponernos en contacto con usted"
                       placeholder="Por favor ingrese un correo para ponernos en contacto con usted"/>
                <div class="validation"></div>
              </li>
              <li>
                <label>Mensaje :</label>
                <textarea class="form-control input-lg" rows="8" name="message" data-rule="required"
                          data-msg="Por favor redacte su pregunta duda o inquietud"
                          placeholder="Por favor redacte su pregunta duda o inquietud ..."></textarea>
                <div class="validation"></div>
              </li>
              <li>
                <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary']) ?>
              </li>
            </ul>
          </form>
        </div>
      </div>
      <div class="col-md-6 half-column set-right">
        <div class="fluid">
          <img src="<?= \yii\helpers\Url::to("@web/theme/img/img-app02.png") ?>" class="img-responsive" alt=""/>
        </div>
      </div>
    </div>
  </div>
</section>

views/sitio/login.php
<?php
/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 12/01/17
 * Time: 12:09 AM
 * @var $this \yii\web\View
 * @var $model \app\models\LoginForm
 * @var $empresas \app\models\EmpresaTelecliente[]
 */
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Ingresar - Teleclientes.com';
?>
<section id="home" class="home-section default-bg color2">
  <div class="container">
    <div class="row">
      <div class="col-md-6 marginbot40">
        <img src="<?= \yii\helpers\Url::to("@web/theme/img/slider/mobile-phone.png") ?>" class="img-responsive"
             alt=""/>
      </div>
      <div class="col-md-6">
        <div class="headline">
          <h4>Teleclientes - Ingresa</h4>
        </div>
        <?php $form = ActiveForm::begin() ?>
        <?= $form->field($model, 'empresa_id', ['labelOptions' => ['class' => 'label-white'],
          'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Seleccione su empresa']])
          ->dropDownList(\yii\helpers\ArrayHelper::map($empresas, 'id', 'nombre'), ['prompt' => 'Seleccione'])
          ->hint('Nombre de usuario sin espacios, par ingresar') ?>
        <?= $form->field($model, 'username', ['labelOptions' => ['class' => 'label-white'],
          'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Nombre de usuario']]) ?>
        <?= $form->field($model, 'password', ['labelOptions' => ['class' => 'label-white'],
          'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'contraseña']])->passwordInput() ?>
        <?= $form->field($model, 'rememberMe', ['labelOptions' => ['class' => 'label-white']])->checkbox() ?>

        <div class="form-group row">
          <div class="col-lg-4">
            <?= Html::submitButton('Enviar', ['class' => 'btn btn-default btn-xs btn-block']) ?>
          </div>
          <div class="col-lg-8">
            <?= Html::a('Olvide mi contraseña', ['/sitio/recordar-contrasena'], ['class' => 'btn btn-default btn-xs btn-block']) ?>
          </div>
        </div>
        <div class="form-group">
          <?= Html::a('Registre su empresa y pruebe gratis teleclientes por 2 meses', ['/sitio/registrar'],['class' => 'btn btn-default btn-xs']) ?>
        </div>
        <?php ActiveForm::end() ?>
      </div>
    </div>
  </div>
</section>

views/sitio/recordar_contrasena.php
<?php
/**
 * User: jhon
 * Date: 12/01/17
 * Time: 12:09 AM
 * @var $this \yii\web\View
 * @var $model \app\models\UserRepass
 * @var $empresas \app\models\EmpresaTelecliente[]
 */
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Html;

$this->title = 'Recordar contraseña - Teleclientes.com';
?>
<section id="home" class="home-section default-bg color2">
    <div class="container">
        <div class="row">
            <div class="col-md-6 marginbot40">
                <img src="<?= \yii\helpers\Url::to("@web/theme/img/slider/mobile-phone.png") ?>" class="img-responsive"
                     alt=""/>
            </div>
            <div class="col-md-6">
                <div class="headline">
                    <h5>Teleclientes - Recordar contraseña</h5>
                </div>
                <?php $form = ActiveForm::begin() ?>
                <?= $form->field($model, 'empresa_id', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Seleccione su empresa']])
                    ->dropDownList(\yii\helpers\ArrayHelper::map($empresas, 'id', 'nombre'), ['prompt' => 'Seleccione']) ?>
                <?= $form->field($model, 'correo', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Correo de usuario']]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'captchaAction' => ['sitio/captcha'],
                    'template' => '
                                <div class="row">
                                    <div class="col-lg-6">
                                    {image}<br>
                                    <small>Click en la imagen para cambiar</small>
                                    </div>
                                    <div class="col-lg-6">{input}</div>
                                </div>',
                    'options'=>['class'=>'form-control input-lg','placeholder'=>'Ingrese el contenido de la imagen'],
                ])->label(false)->hint('') ?>
                <div class="form-group">
                    <?= Html::submitButton('Enviar solicitud', ['class' => 'btn btn-default btn-lg']) ?>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</section>

views/sitio/recuperar_contrasena.php
<?php
/**
 * User: jhon
 * Date: 12/01/17
 * Time: 12:09 AM
 * @var $this \yii\web\View
 * @var $model \app\models\Newpass
 */
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Html;

$this->title = 'Recordar contraseña - Teleclientes.com';
?>
<section id="home" class="home-section default-bg color2">
    <div class="container">
        <div class="row">
            <div class="col-md-6 marginbot40">
                <img src="<?= \yii\helpers\Url::to("@web/theme/img/slider/mobile-phone.png") ?>" class="img-responsive"
                     alt=""/>
            </div>
            <div class="col-md-6">
                <div class="headline">
                    <h5>Teleclientes - Recordar contraseña</h5>
                </div>
                <?php $form = ActiveForm::begin() ?>
                <?= $form->field($model, 'password', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Ingrese su nueva contraseña']]) ?>
                <?= $form->field($model, 'password2', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Correo de usuario']]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Confirmar', ['class' => 'btn btn-default btn-lg']) ?>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</section>

views/sitio/registro.php
<?php
/**
 * Created by PhpStorm.
 * User: jhon
 * Date: 12/01/17
 * Time: 12:09 AM
 * @var $this \yii\web\View
 * @var $registro \app\models\SignupForm
 * @var $empresa \app\models\EmpresaTelecliente
 */
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
$this->title = 'Registrate en Teleclientes.com';
?>
<section id="home" class="home-section default-bg color2">
    <div class="container">
        <div class="row">
            <div class="col-md-6 marginbot40">
                <img src="<?= \yii\helpers\Url::to("@web/theme/img/slider/mobile-phone.png") ?>" class="img-responsive"
                     alt=""/>
            </div>
            <div class="col-md-6">
                <div class="headline">
                    <h4>Teleclientes - Registrate</h4>
                </div>
                <?php $form = ActiveForm::begin() ?>
                <?= $form->field($registro, 'username', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Nombre de usuario']])
                    ->hint('Nombre de usuario sin espacios, par ingresar') ?>
                <?= $form->field($registro, 'nombres', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Nombre completo']])
                    ->hint('Por favor indique su nombre') ?>
                <?= $form->field($registro, 'email', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Email']]) ?>
                <?= $form->field($registro, 'password', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Contraseña']])
                    ->passwordInput() ?>
                <?= $form->field($empresa, 'nombre', ['labelOptions' => ['class' => 'label-white'],
                    'inputOptions' => ['class' => 'form-control input-lg', 'placeholder' => 'Nombre de su empresa']])
                    ->hint('indique el nombre de su empresa') ?>
                <div class="form-group">
                    <?= Html::submitButton('Enviar', ['class' => 'btn btn-default btn-lg']) ?>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</section>